/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-application-conventions")
    id("com.gradleup.shadow") version "8.3.3"
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":network"))
}

application {
    // Define the main class for the application.
    mainClass = "com.github.coffeeworlds.client.Client"
}
