/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-application-conventions")
    id("com.gradleup.shadow") version "8.3.3"
    id("com.adarshr.test-logger") version "4.0.0"
    id("com.diffplug.spotless") version "7.0.0.BETA4"
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":network"))
    implementation(project(":huffman"))
}

application {
    // Define the main class for the application.
    mainClass = "com.github.coffeeworlds.client.Client"
}

spotless {
    java {
        importOrder()
        googleJavaFormat()
    }
}
