/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-library-conventions")
}

// link huffman here once its created at the root of the repo

// dependencies {
//     api(project(":huffman"))
// }
